name: Test code and app
on: 
  - workflow_dispatch
  - push
#   pull_request:
#     paths:
#       - src/**
#       - config/**
#       - training/**
# #      - application/**
#       - .github/workflows/test_training.yaml
jobs:
  test_model:
    name: Test processed code and model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10
          cache: pip

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install packages
        run: pip install -r dev-requirements.txt

      - name: Train model
        run: python ./training/src/main.py

      - name: Test processed code and ML model
        run: pytest training/tests

      - name: Serve the app locally and run app tests
        run: |
          python ./application/src/create_service.py &
          sleep 10
          pytest application/tests

      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1.9.1
        with:
          secret: ${{ secrets.APPROVE_TOKEN }}
          approvers: DaitaOps
          minimum-approvals: 1
          issue-title: "Checking training metrics and tests"
          issue-body: "Please check the obtained scores and approve accordingly"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

      - name: Amazon ECR "Login" Action for GitHub Actions
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      #### Deploy API container ####
      - name: Build API Docker Image
        run: docker build -t my-test-api -f Dockerfile.api .

      - name: Tag API Docker Image
        run: docker tag my-test-api:latest ${{ steps.login-ecr.outputs.registry }}/mlops-innotech-api:latest

      - name: Push API Docker Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/mlops-innotech-api:latest

      #### Deploy UI container ####
      - name: Build UI Docker Image
        run: docker build -t my-test-ui -f Dockerfile.ui .

      - name: Tag UI Docker Image
        run: docker tag my-test-ui:latest ${{ steps.login-ecr.outputs.registry }}/mlops-innotech-ui:latest

      - name: Push UI Docker Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/mlops-innotech-ui:latest


